blank_issues_enabled: true
contact_links:
  - name: 🔒 Security Vulnerabilities
    url: https://hackerone.com/nodejs
    about: Report security vulnerabilities through the Node.js Bug Bounty Program
  - name: 💬 General Discussion
    url: https://github.com/nodejs/node/discussions
    about: Ask questions and discuss ideas with the Node.js community
  - name: 📚 Documentation Issues
    url: https://github.com/nodejs/node/issues
    about: Report issues with Node.js documentation or API references