import { CACHE_HEADERS } from '../constants/cache';
import latestVersions from '../constants/latestVersions.json' assert { type: 'json' };
import { isDirectoryPath } from './path';

// Files whose contents change without a version/URL change.
const MUTABLE_FILENAMES = new Set([
  'index.json',
  'index.tab',
  'llms.txt',
  'node-config-schema.json',
]);

// Moving aliases (`latest`, `latest-v20.x`, `latest-argon`, `node-latest.tar.gz`,
//  …). Each key of `latestVersions` is a path segment that points at a different
//  release over time, so anything served under one must not be cached immutably.
//  Sourcing this from `latestVersions` keeps it in sync with the routes
//  registered in `routes/index.ts`.
const MOVING_ALIASES = new Set(Object.keys(latestVersions));

/**
 * Decides whether a response can be cached immutably (effectively forever) based
 *  on the ORIGINAL (unsubstituted) request pathname.
 *
 * Most content we serve is immutable: a published release asset under a concrete
 *  version never changes. The exceptions are resources whose contents change
 *  while their URL stays the same:
 *  - directory listings (a new file can appear at any time)
 *  - the `/api/*` route (always serves the current `latest` version's docs)
 *  - everything under `/metrics/` (regenerated by the download-counts run)
 *  - `latest`/`latest-vXX.x`/`latest-<codename>` aliases (point at a different
 *    release over time)
 *  - index/metadata files like `index.json`
 *
 * @param pathname Original request pathname (use `unsubstitutedUrl` if present)
 */
export function isImmutablePath(pathname: string): boolean {
  // Directory listings change as files are added.
  if (isDirectoryPath(pathname)) {
    return false;
  }

  // `/api/*` always serves the current `latest` version's docs.
  if (pathname === '/api' || pathname.startsWith('/api/')) {
    return false;
  }

  // The periodic download-counts run rewrites files under `/metrics/` at stable
  //  URLs: the `summaries/<type>.csv`/`.png` aggregates every run, and
  //  `logs/nodejs.org-access.log.csv` for the current (not yet final) day. The
  //  per-day files next to them are final, but they're cheap to revalidate and
  //  low-traffic, so the whole tree takes the mutable policy.
  if (pathname === '/metrics' || pathname.startsWith('/metrics/')) {
    return false;
  }

  const segments = pathname.split('/');

  // `/dist/latest/`, `/docs/latest-v18.x/`, `/dist/latest-argon/`, etc. are
  //  moving aliases. Any path segment matching a known alias is mutable.
  if (segments.some(segment => MOVING_ALIASES.has(segment))) {
    return false;
  }

  const filename = segments[segments.length - 1];

  // `SHASUMS*.txt` and their `.asc`/`.sig` signatures are regenerated in an
  //  already-published version directory by the post-promotion re-sha and
  //  signing steps, so they can change after we've already served them.
  if (filename.startsWith('SHASUMS')) {
    return false;
  }

  if (MUTABLE_FILENAMES.has(filename)) {
    return false;
  }

  return true;
}

/**
 * Single source of truth for the `cache-control` header on a response.
 *
 * Errors get the `failure` policy (`no-store`), so they aren't cached at all.
 *
 * 200, 206 and 304 all get the path's normal policy. A 304 must carry the same
 *  `cache-control` the 200 would have: per RFC 9111 4.3.4 its header fields
 *  update the stored response, so sending `no-store` on a 304 would evict the
 *  very entry being revalidated. 206 carries it for the same reason - the range
 *  belongs to a cacheable representation.
 */
export function cacheControlFor(pathname: string, statusCode: number): string {
  if (statusCode >= 400) {
    return CACHE_HEADERS.failure;
  }

  return isImmutablePath(pathname)
    ? CACHE_HEADERS.immutable
    : CACHE_HEADERS.mutable;
}
