name: Auto-merge PRs

on:
  schedule:
    - cron: '*/15 * * * *'
  workflow_dispatch:

permissions:
  pull-requests: write
  contents: write

jobs:
  auto-merge:
    if: github.repository == 'nodejs/release-cloudflare-worker'
    runs-on: ubuntu-latest

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@fa2e9d605c4eeb9fcad4c99c224cee0c6c7f3594 # v2.16.0
        with:
          egress-policy: audit

      - uses: nodejs/web-team/actions/auto-merge-prs@b087df186d25f8792fb85cc7794f68718726b8ee
        with:
          merge-method: squash
