name: Deploy Worker

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy Cloudflare Worker
    timeout-minutes: 5
    runs-on: ubuntu-latest

    steps:
      - uses: step-security/harden-runner@002fdce3c6a235733a90a27c80493a3241e56863 # v2.12.1
        with:
          egress-policy: block
          allowed-endpoints: >
            api.cloudflare.com:443
            api.github.com:443
            github.com:443
            hooks.slack.com:443
            registry.npmjs.org:443

      - name: Git Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
  
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: 'npm'

      - name: Install Dependencies
        run: npm install

      - name: Deploy to Staging
        if: github.event_name == 'push'
        uses: cloudflare/wrangler-action@da0e0dfe58b7a431659754fdf3f186c529afbe65
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          command: deploy --env staging

      - name: Deploy to Production
        if: github.event_name == 'workflow_dispatch'
        uses: cloudflare/wrangler-action@da0e0dfe58b7a431659754fdf3f186c529afbe65
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          command: deploy --env prod

      - name: Alert on Failure
        if: failure() && github.repository == 'nodejs/release-cloudflare-worker'
        uses: rtCamp/action-slack-notify@e31e87e03dd19038e411e38ae27cbad084a90661 # 2.3.3
        env:
          SLACK_COLOR: '#DE512A'
          SLACK_ICON: https://github.com/nodejs.png?size=48
          SLACK_TITLE: Deployment failed (${{ github.ref }})
          SLACK_MESSAGE: A deployment of the Release Worker has failed.
          SLACK_USERNAME: nodejs-bot
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
