name: Deploy Worker

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy Cloudflare Worker
    timeout-minutes: 5
    runs-on: ubuntu-latest

    steps:
      - name: Git Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683

      - name: Deploy to Staging
        if: github.event_name == 'push'
        uses: cloudflare/wrangler-action@da0e0dfe58b7a431659754fdf3f186c529afbe65
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          command: deploy --env staging

      - name: Deploy to Production
        if: github.event_name == 'workflow_dispatch'
        uses: cloudflare/wrangler-action@da0e0dfe58b7a431659754fdf3f186c529afbe65
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          command: deploy --env prod
        
